FROM scratch

# Add the binary to the root dir
ADD main /

# Set environment variables
ENV LOGXI *=INF
ENV LOGXI_COLORS *=black,key=black+h,message=blue,TRC,DBG,WRN=red+h,INF=green,ERR=red+h,maxcol=1000
ENV LOGXI_FORMAT happy,t=2006-01-02 15:04:05.000000
ENV GIN_MODE release

# Expose ports
EXPOSE 80

# Run command
CMD ["/main", "-addr=:80"]
